server:
  port: 8081

spring:
  application:
    name: BitBucketStats
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false

bitbucket:
  api-base: "https://api.bitbucket.org/2.0"
